# Generated by Django 3.0.2 on 2020-05-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=10000)),
                ('address', models.TextField(max_length=10000)),
                ('BHK', models.CharField(max_length=5)),
                ('image', models.ImageField(upload_to='')),
                ('area', models.PositiveIntegerField()),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('parking', models.BooleanField(default=0)),
                ('furnishing', models.BooleanField(default=0)),
                ('small_thumbnail', models.ImageField(upload_to='')),
                ('amenities', models.CharField(choices=[('Gym', 'Gym'), ('Swimming Pool', 'Swimming Pool'), ('Garden', 'Garden')], max_length=100)),
            ],
        ),
    ]
