# Generated by Django 3.0.2 on 2020-05-27 07:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_information',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Gym', 'Gym'), ('Swimming Pool', 'Swimming Pool'), ('Garden', 'Garden')], max_length=24),
        ),
    ]
