# Generated by Django 3.0.2 on 2020-05-27 07:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20200527_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_information',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Gym', 'Gym'), ('Swimming Pool', 'Swimming Pool'), ('Garden', 'Garden'), ('Club House', 'Club House'), ('Cafe Area', 'Cafe Area'), ('Children Play Area', 'Children Play Area'), ('Intercom', 'Intercom')], max_length=73),
        ),
    ]
