# Generated by Django 3.0.2 on 2020-05-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_information_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_information',
            name='area',
            field=models.CharField(default='0sqft', max_length=500),
        ),
    ]
