# Generated by Django 3.0.2 on 2020-06-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20200602_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_information',
            name='images',
        ),
        migrations.DeleteModel(
            name='ImagesProperty',
        ),
    ]
