# Generated by Django 3.0.2 on 2020-06-02 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_auto_20200602_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_information',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('propertY', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='properties.Property_Information')),
            ],
        ),
    ]
